#ifndef SEGMENTATIONS_FORWARD_HPP
#define SEGMENTATIONS_FORWARD_HPP

class LinearCartesian1D_Segmentation;
class LinearCartesian2D_Segmentation;
class LinearCartesian3D_Segmentation;
class LinearCylindrical3D_Segmentation;
class LinearPolar2D_Segmentation;
class LinearSpherical3D_Segmentation;

class TriangularCartesian2D_Segmentation;
class TriangularCartesian3D_Segmentation;
class TriangularCylindrical3D_Segmentation;
class TriangularPolar2D_Segmentation;
class TriangularSpherical3D_Segmentation;

class QuadrilateralCartesian2D_Segmentation;
class QuadrilateralCartesian3D_Segmentation;
class QuadrilateralCylindrical3D_Segmentation;
class QuadrilateralPolar2D_Segmentation;
class QuadrilateralSpherical3D_Segmentation;

class TetrahedralCartesian3D_Segmentation;
class TetrahedralCylindrical3D_Segmentation;
class TetrahedralSpherical3D_Segmentation;

#endif /* end of include guard: SEGMENTATIONS_FORWARD_HPP */
